# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fdw.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fdw.proto',
  package='PostgresFdw',
  syntax='proto3',
  serialized_pb=_b('\n\tfdw.proto\x12\x0bPostgresFdw\"\xcf\x01\n\x10\x43olumnDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03oid\x18\x02 \x01(\x05\x12\x0b\n\x03mod\x18\x03 \x01(\x05\x12\x10\n\x08typeName\x18\x04 \x01(\t\x12\x14\n\x0c\x62\x61seTypeName\x18\x05 \x01(\t\x12;\n\x07options\x18\x06 \x03(\x0b\x32*.PostgresFdw.ColumnDefinition.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbd\x01\n\x17PerformForeignScanInput\x12.\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x1d.PostgresFdw.ColumnDefinition\x12\x42\n\x07options\x18\x02 \x03(\x0b\x32\x31.PostgresFdw.PerformForeignScanInput.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9a\x02\n\x03Row\x12,\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1c.PostgresFdw.Row.FieldsEntry\x1a\x9a\x01\n\x08RowValue\x12\x15\n\x0bstringValue\x18\x01 \x01(\tH\x00\x12\x14\n\nfloatValue\x18\x02 \x01(\x02H\x00\x12\x15\n\x0b\x64oubleValue\x18\x03 \x01(\x01H\x00\x12\x12\n\x08intValue\x18\x04 \x01(\x05H\x00\x12\x13\n\tlongValue\x18\x05 \x01(\x03H\x00\x12\x13\n\tboolValue\x18\x06 \x01(\x08H\x00\x42\x0c\n\ntest_oneof\x1aH\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.PostgresFdw.Row.RowValue:\x02\x38\x01\":\n\x18PerformForeignScanOutput\x12\x1e\n\x04rows\x18\x01 \x03(\x0b\x32\x10.PostgresFdw.Row2t\n\x0bPostgresFdw\x12\x65\n\x12PerformForeignScan\x12$.PostgresFdw.PerformForeignScanInput\x1a%.PostgresFdw.PerformForeignScanOutput\"\x00\x30\x01\x62\x06proto3')
)




_COLUMNDEFINITION_OPTIONSENTRY = _descriptor.Descriptor(
  name='OptionsEntry',
  full_name='PostgresFdw.ColumnDefinition.OptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PostgresFdw.ColumnDefinition.OptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PostgresFdw.ColumnDefinition.OptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=234,
)

_COLUMNDEFINITION = _descriptor.Descriptor(
  name='ColumnDefinition',
  full_name='PostgresFdw.ColumnDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PostgresFdw.ColumnDefinition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oid', full_name='PostgresFdw.ColumnDefinition.oid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mod', full_name='PostgresFdw.ColumnDefinition.mod', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='typeName', full_name='PostgresFdw.ColumnDefinition.typeName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseTypeName', full_name='PostgresFdw.ColumnDefinition.baseTypeName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='PostgresFdw.ColumnDefinition.options', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COLUMNDEFINITION_OPTIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=234,
)


_PERFORMFOREIGNSCANINPUT_OPTIONSENTRY = _descriptor.Descriptor(
  name='OptionsEntry',
  full_name='PostgresFdw.PerformForeignScanInput.OptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PostgresFdw.PerformForeignScanInput.OptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PostgresFdw.PerformForeignScanInput.OptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=234,
)

_PERFORMFOREIGNSCANINPUT = _descriptor.Descriptor(
  name='PerformForeignScanInput',
  full_name='PostgresFdw.PerformForeignScanInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='PostgresFdw.PerformForeignScanInput.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='PostgresFdw.PerformForeignScanInput.options', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERFORMFOREIGNSCANINPUT_OPTIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=426,
)


_ROW_ROWVALUE = _descriptor.Descriptor(
  name='RowValue',
  full_name='PostgresFdw.Row.RowValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stringValue', full_name='PostgresFdw.Row.RowValue.stringValue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatValue', full_name='PostgresFdw.Row.RowValue.floatValue', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doubleValue', full_name='PostgresFdw.Row.RowValue.doubleValue', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intValue', full_name='PostgresFdw.Row.RowValue.intValue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longValue', full_name='PostgresFdw.Row.RowValue.longValue', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolValue', full_name='PostgresFdw.Row.RowValue.boolValue', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='test_oneof', full_name='PostgresFdw.Row.RowValue.test_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=483,
  serialized_end=637,
)

_ROW_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='PostgresFdw.Row.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PostgresFdw.Row.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PostgresFdw.Row.FieldsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=711,
)

_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='PostgresFdw.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='PostgresFdw.Row.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ROW_ROWVALUE, _ROW_FIELDSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=711,
)


_PERFORMFOREIGNSCANOUTPUT = _descriptor.Descriptor(
  name='PerformForeignScanOutput',
  full_name='PostgresFdw.PerformForeignScanOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='PostgresFdw.PerformForeignScanOutput.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=713,
  serialized_end=771,
)

_COLUMNDEFINITION_OPTIONSENTRY.containing_type = _COLUMNDEFINITION
_COLUMNDEFINITION.fields_by_name['options'].message_type = _COLUMNDEFINITION_OPTIONSENTRY
_PERFORMFOREIGNSCANINPUT_OPTIONSENTRY.containing_type = _PERFORMFOREIGNSCANINPUT
_PERFORMFOREIGNSCANINPUT.fields_by_name['columns'].message_type = _COLUMNDEFINITION
_PERFORMFOREIGNSCANINPUT.fields_by_name['options'].message_type = _PERFORMFOREIGNSCANINPUT_OPTIONSENTRY
_ROW_ROWVALUE.containing_type = _ROW
_ROW_ROWVALUE.oneofs_by_name['test_oneof'].fields.append(
  _ROW_ROWVALUE.fields_by_name['stringValue'])
_ROW_ROWVALUE.fields_by_name['stringValue'].containing_oneof = _ROW_ROWVALUE.oneofs_by_name['test_oneof']
_ROW_ROWVALUE.oneofs_by_name['test_oneof'].fields.append(
  _ROW_ROWVALUE.fields_by_name['floatValue'])
_ROW_ROWVALUE.fields_by_name['floatValue'].containing_oneof = _ROW_ROWVALUE.oneofs_by_name['test_oneof']
_ROW_ROWVALUE.oneofs_by_name['test_oneof'].fields.append(
  _ROW_ROWVALUE.fields_by_name['doubleValue'])
_ROW_ROWVALUE.fields_by_name['doubleValue'].containing_oneof = _ROW_ROWVALUE.oneofs_by_name['test_oneof']
_ROW_ROWVALUE.oneofs_by_name['test_oneof'].fields.append(
  _ROW_ROWVALUE.fields_by_name['intValue'])
_ROW_ROWVALUE.fields_by_name['intValue'].containing_oneof = _ROW_ROWVALUE.oneofs_by_name['test_oneof']
_ROW_ROWVALUE.oneofs_by_name['test_oneof'].fields.append(
  _ROW_ROWVALUE.fields_by_name['longValue'])
_ROW_ROWVALUE.fields_by_name['longValue'].containing_oneof = _ROW_ROWVALUE.oneofs_by_name['test_oneof']
_ROW_ROWVALUE.oneofs_by_name['test_oneof'].fields.append(
  _ROW_ROWVALUE.fields_by_name['boolValue'])
_ROW_ROWVALUE.fields_by_name['boolValue'].containing_oneof = _ROW_ROWVALUE.oneofs_by_name['test_oneof']
_ROW_FIELDSENTRY.fields_by_name['value'].message_type = _ROW_ROWVALUE
_ROW_FIELDSENTRY.containing_type = _ROW
_ROW.fields_by_name['fields'].message_type = _ROW_FIELDSENTRY
_PERFORMFOREIGNSCANOUTPUT.fields_by_name['rows'].message_type = _ROW
DESCRIPTOR.message_types_by_name['ColumnDefinition'] = _COLUMNDEFINITION
DESCRIPTOR.message_types_by_name['PerformForeignScanInput'] = _PERFORMFOREIGNSCANINPUT
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['PerformForeignScanOutput'] = _PERFORMFOREIGNSCANOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ColumnDefinition = _reflection.GeneratedProtocolMessageType('ColumnDefinition', (_message.Message,), dict(

  OptionsEntry = _reflection.GeneratedProtocolMessageType('OptionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _COLUMNDEFINITION_OPTIONSENTRY,
    __module__ = 'fdw_pb2'
    # @@protoc_insertion_point(class_scope:PostgresFdw.ColumnDefinition.OptionsEntry)
    ))
  ,
  DESCRIPTOR = _COLUMNDEFINITION,
  __module__ = 'fdw_pb2'
  # @@protoc_insertion_point(class_scope:PostgresFdw.ColumnDefinition)
  ))
_sym_db.RegisterMessage(ColumnDefinition)
_sym_db.RegisterMessage(ColumnDefinition.OptionsEntry)

PerformForeignScanInput = _reflection.GeneratedProtocolMessageType('PerformForeignScanInput', (_message.Message,), dict(

  OptionsEntry = _reflection.GeneratedProtocolMessageType('OptionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PERFORMFOREIGNSCANINPUT_OPTIONSENTRY,
    __module__ = 'fdw_pb2'
    # @@protoc_insertion_point(class_scope:PostgresFdw.PerformForeignScanInput.OptionsEntry)
    ))
  ,
  DESCRIPTOR = _PERFORMFOREIGNSCANINPUT,
  __module__ = 'fdw_pb2'
  # @@protoc_insertion_point(class_scope:PostgresFdw.PerformForeignScanInput)
  ))
_sym_db.RegisterMessage(PerformForeignScanInput)
_sym_db.RegisterMessage(PerformForeignScanInput.OptionsEntry)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(

  RowValue = _reflection.GeneratedProtocolMessageType('RowValue', (_message.Message,), dict(
    DESCRIPTOR = _ROW_ROWVALUE,
    __module__ = 'fdw_pb2'
    # @@protoc_insertion_point(class_scope:PostgresFdw.Row.RowValue)
    ))
  ,

  FieldsEntry = _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ROW_FIELDSENTRY,
    __module__ = 'fdw_pb2'
    # @@protoc_insertion_point(class_scope:PostgresFdw.Row.FieldsEntry)
    ))
  ,
  DESCRIPTOR = _ROW,
  __module__ = 'fdw_pb2'
  # @@protoc_insertion_point(class_scope:PostgresFdw.Row)
  ))
_sym_db.RegisterMessage(Row)
_sym_db.RegisterMessage(Row.RowValue)
_sym_db.RegisterMessage(Row.FieldsEntry)

PerformForeignScanOutput = _reflection.GeneratedProtocolMessageType('PerformForeignScanOutput', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMFOREIGNSCANOUTPUT,
  __module__ = 'fdw_pb2'
  # @@protoc_insertion_point(class_scope:PostgresFdw.PerformForeignScanOutput)
  ))
_sym_db.RegisterMessage(PerformForeignScanOutput)


_COLUMNDEFINITION_OPTIONSENTRY.has_options = True
_COLUMNDEFINITION_OPTIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PERFORMFOREIGNSCANINPUT_OPTIONSENTRY.has_options = True
_PERFORMFOREIGNSCANINPUT_OPTIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_ROW_FIELDSENTRY.has_options = True
_ROW_FIELDSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_POSTGRESFDW = _descriptor.ServiceDescriptor(
  name='PostgresFdw',
  full_name='PostgresFdw.PostgresFdw',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=773,
  serialized_end=889,
  methods=[
  _descriptor.MethodDescriptor(
    name='PerformForeignScan',
    full_name='PostgresFdw.PostgresFdw.PerformForeignScan',
    index=0,
    containing_service=None,
    input_type=_PERFORMFOREIGNSCANINPUT,
    output_type=_PERFORMFOREIGNSCANOUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTGRESFDW)

DESCRIPTOR.services_by_name['PostgresFdw'] = _POSTGRESFDW

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PostgresFdwStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.PerformForeignScan = channel.unary_stream(
          '/PostgresFdw.PostgresFdw/PerformForeignScan',
          request_serializer=PerformForeignScanInput.SerializeToString,
          response_deserializer=PerformForeignScanOutput.FromString,
          )


  class PostgresFdwServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def PerformForeignScan(self, request, context):
      """rpc GetForeignRelSize(GetForeignRelSizeInput) returns (GetForeignRelSizeOutput) {}
      rpc GetForeignPaths(GetForeignPathsInput) returns (GetForeignPathsOutput) {}
      rpc GetForeignPlan(GetForeignPlanInput) returns (GetForeignPlanOutput) {}
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PostgresFdwServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PerformForeignScan': grpc.unary_stream_rpc_method_handler(
            servicer.PerformForeignScan,
            request_deserializer=PerformForeignScanInput.FromString,
            response_serializer=PerformForeignScanOutput.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'PostgresFdw.PostgresFdw', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPostgresFdwServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def PerformForeignScan(self, request, context):
      """rpc GetForeignRelSize(GetForeignRelSizeInput) returns (GetForeignRelSizeOutput) {}
      rpc GetForeignPaths(GetForeignPathsInput) returns (GetForeignPathsOutput) {}
      rpc GetForeignPlan(GetForeignPlanInput) returns (GetForeignPlanOutput) {}
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPostgresFdwStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def PerformForeignScan(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """rpc GetForeignRelSize(GetForeignRelSizeInput) returns (GetForeignRelSizeOutput) {}
      rpc GetForeignPaths(GetForeignPathsInput) returns (GetForeignPathsOutput) {}
      rpc GetForeignPlan(GetForeignPlanInput) returns (GetForeignPlanOutput) {}
      """
      raise NotImplementedError()


  def beta_create_PostgresFdw_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('PostgresFdw.PostgresFdw', 'PerformForeignScan'): PerformForeignScanInput.FromString,
    }
    response_serializers = {
      ('PostgresFdw.PostgresFdw', 'PerformForeignScan'): PerformForeignScanOutput.SerializeToString,
    }
    method_implementations = {
      ('PostgresFdw.PostgresFdw', 'PerformForeignScan'): face_utilities.unary_stream_inline(servicer.PerformForeignScan),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_PostgresFdw_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('PostgresFdw.PostgresFdw', 'PerformForeignScan'): PerformForeignScanInput.SerializeToString,
    }
    response_deserializers = {
      ('PostgresFdw.PostgresFdw', 'PerformForeignScan'): PerformForeignScanOutput.FromString,
    }
    cardinalities = {
      'PerformForeignScan': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'PostgresFdw.PostgresFdw', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
